---
title: "205-filterFirst"
author: "Linder Wendt"
date: "3/5/2017"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
library(stringr)
library(hexbin)
raw_nox <- read.csv("https://raw.githubusercontent.com/wyattjssmith/CMSC205-Project/master/Clean_NOx.csv?token=AX51v2i8LsGZFEkRiUAxoVxeA7GFQicpks5YxeRPwA%3D%3D")
```
Joining Date and Time
```{r}
#Already ran these once, running str_sub again will change Time slot again
raw_nox$Time <- as.character(raw_nox$Time)
raw_nox$Time <- str_sub(raw_nox$Time, 1, nchar(raw_nox$Time) - 3)

#Join together Date and Time
raw_nox <- unite(raw_nox, date_time, Date, Time, sep = " ")

#Make date_time a date
raw_nox$date_time <- mdy_hm(raw_nox$date_time)

#Other stuff imported from original doc
nox <- raw_nox

#Make everything numeric!
nox$X <- as.numeric(nox$X)
nox$i.Model.405 <- as.numeric(nox$i.Model.405)
nox$NO2 <- as.numeric(nox$NO2)
nox$NO <- as.numeric(nox$NO)
nox$NOx <- as.numeric(nox$NOx)
nox$ZnO2 <- as.numeric(nox$ZnO2)
nox$ZnO <- as.numeric(nox$ZnO)
nox$Cf <- as.numeric(nox$Cf)
nox$Cell.Temp <- as.numeric(nox$Cell.Temp)
nox$Cell.Pressure <- as.numeric(nox$Cell.Pressure)
nox$Overflow <- as.numeric(nox$Overflow)
nox$Cell.Flow <- as.numeric(nox$Cell.Flow)
nox$Ozone.Flow <- as.numeric(nox$Ozone.Flow)
nox$PDVa <- as.numeric(nox$PDVa)
nox$PDVb <- as.numeric(nox$PDVb)
nox$PDVo3 <- as.numeric(nox$PDVo3)
nox$Scrubber.Temp <- as.numeric(nox$Scrubber.Temp)
#Don't do this!!!!!!!!!! nox$date_time <- as.numeric(nox$date_time)
nox$Mode <- as.numeric(nox$Mode)

#Group each data set into minutes and call it new_nox
new_nox<-nox%>%
  group_by(date_time)%>%
summarize('X' = mean(X), 'i.Model.405' = mean(i.Model.405), 'NO2' = mean(NO2), 'NO' = mean(NO), 'NOx' = mean(NOx), 'ZnO2' = mean(ZnO2), 'ZnO' = mean(ZnO), 'Cf' = mean(Cf), 'Cell.Temp' = mean(Cell.Temp), 'Cell.Pressure' = mean(Cell.Pressure), 'Overflow' = mean(Overflow), 'Cell.Flow' = mean(Cell.Flow), 'Ozone.Flow' = mean(Ozone.Flow), 'PDVa' = mean(PDVa), 'PDVb' = mean(PDVb), 'PDVo3' = mean(PDVo3), 'Scrubber.Temp' = mean(Scrubber.Temp), 'Mode' = mean(Mode))


```
Graphing results
```{r}
raw_nox%>%
  ggplot(aes(x = date_time, y = Cell.Flow)) + geom_point(color = 'purple')

```
Filter Results based on extremities of previous graphs
```{r}
raw_nox <- filter(raw_nox, raw_nox$Cell.Pressure > 700)
raw_nox <- filter(raw_nox, raw_nox$NO2 < 4000)
raw_nox <- filter(raw_nox, raw_nox$Cell.Flow > 1675)
```


